context:
  name: cargo-insta
  version: "1.43.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/mitsuhiko/insta/releases/download/${{ version }}/source.tar.gz
  sha256: c890349b7fb9c55d66a57a0eb2fe086e15d71fcfe90fcb7c667c1fdb084e98c0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - cargo-insta --help
about:
  homepage: https://insta.rs/
  summary: 'A snapshot testing library for Rust'
  description: |
    Snapshots tests (also sometimes called approval tests) are tests that
    assert values against a reference value (the snapshot). This is similar
    to how `assert_eq!` lets you compare a value against a reference value but
    unlike simple string assertions, snapshot tests let you test against complex
    values and come with comprehensive tools to review changes.

    Snapshot tests are particularly useful if your reference values are very
    large or change often.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/mitsuhiko/insta

extra:
  recipe-maintainers:
    - Hofer-Julian
